name: Build and Push

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger only on tag pushes
    branches:
      - "main"

env:
  Dockerfile: Dockerfile
  PROJECTS: gpu-cloud

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.1.1
        with:
          cosign-release: 'v2.1.1'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to Harbor registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Get tag name without prefix
        id: get_tag_name
        run: echo "::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}"

      - name: Build and tag image
        env:
          TAG_NAME: ${{ steps.get_tag_name.outputs.TAG_NAME }}  # Get the tag name without prefix
        run: |
          docker build -t ${{ secrets.HARBOR_REGISTRY }}/${{ env.PROJECTS }}/${{ secrets.REPOSITORY }}:${TAG_NAME} -f Dockerfile .

      - name: Push the image to Harbor
        env:
          TAG_NAME: ${{ steps.get_tag_name.outputs.TAG_NAME }}  # Get the tag name without prefix
        run: |
          docker push ${{ secrets.HARBOR_REGISTRY }}/${{ env.PROJECTS }}/${{ secrets.REPOSITORY }}:${TAG_NAME}

      - name: Sign the published Docker image
        if: github.event_name != 'pull_request'
        env:
          TAG_NAME: ${{ steps.get_tag_name.outputs.TAG_NAME }}  # Get the tag name without prefix
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: |
          echo "${TAG_NAME}" | xargs -I {} cosign sign --yes {}@${DIGEST}
