name: Build and Push

on:
  push:
    tags: [ 'v*.*.*' ]
    branches:
      - "main"

env:
  Dockerfile: Dockerfile.release
  PROJECTS: gpu-cloud

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.1.1 #v3.1.1
        with:
          cosign-release: 'v2.1.1'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0 # v3.0.0

      - uses: docker/login-action@v1
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME  }}
          password: ${{ secrets.HARBOUR_PASSWORD }}
      
      - name: Build and tag image
        env:
          tag_name: ${{ github.ref }}
        run: |
              docker build -t ${{ secrets.HARBOR_REGISTRY }}/${{ env.PROJECTS }}/${{ secrets.REPOSITORY }}:${{ env.tag_name#refs/tags/ }} -f Dockerfile .    

      - name: Push the image to Harbor
        env:
          tag_name: ${{ github.ref }}
        run: docker push ${{ secrets.HARBOR_REGISTRY }}/${{ env.PROJECTS }}/${{ secrets.REPOSITORY }}:${{ env.tag_name#refs/tags/ }}
  
      - name: Sign the published Docker image
        if: github.event_name != 'pull_request'
        env:
          TAGS: ${{ steps.ref }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
