name: Build and Push

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: demo.goharbor.io  # Replace with your Harbor registry URL
  IMAGE_NAME: ${{ github.repository }}
  REPOSITORY: ${{ secrets.REPO }}
  Dockerfile: Dockerfile

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.1.1 #v3.1.1
        with:
          cosign-release: 'v2.1.1'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0 # v3.0.0

      - name: Log into Harbor registry
        if: github.event_name != 'pull_request'
        run: echo "${{ secrets.HARBOR_PASSWORD }}" | docker login ${{ env.REGISTRY }} -u ${{ secrets.HARBOR_USERNAME }} --password-stdin

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.0.0 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build Docker image
        id: build-image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ github.sha }} -f ${{ env.Dockerfile }} .

      - name: Push Docker image to Harbor
        if: github.event_name != 'pull_request'
        run: docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ github.sha }}

      - name: Display Docker image tag pushed to Harbor
        if: github.event_name != 'pull_request'
        run: echo "Docker image pushed to ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ github.sha }}"
